version: '3'
services:
  app:
    image: miaazureacr.azurecr.io/mia_azure:v6
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/miadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: miadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
